### ISSUE TITLE
Update repository readme

### ISSUE THREAD

**Issue by mackeyth** [Chris-plus-alphanumericgibberish/dNAO#833] opened 2020-06-25 01:53 UTC
The repository readme is the same one originally imported from Nethack 3.4.3. It is not descriptive of this repository.

**Comment by mackeyth** [comment] 2020-06-25 02:03
One thing I would like to know is what flavor of C the code is in. Is there a repository standard?

**Comment by NeroOneTrueKing** [comment] 2020-06-25 19:53
The repository readme is a duplicate of #501. If someone else is noticing it I guess it needs addressing now.

There isn't a written standard as far as I'm aware, but there are preferred methods. For example, floats and doubles are avoided.

**Closed as completed** 2020-06-26 14:42 UTC
Labels: duplicate, enhancement, question
