### ISSUE TITLE
Monster spellcasting without line of sight history produces excessive messages

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1789] opened 2021-10-10 04:10 UTC
![image](https://user-images.githubusercontent.com/8377693/136681548-95d6878b-598c-4109-92fe-9ff47fb07b9b.png)
I have never seen this elvenqueen and she has never seen me. We exist between double walls and our gazes have never met. I detect her via my grimtooth. Why is she casting a spell at a spot near me?

**Comment by NeroOneTrueKing** [comment] 2021-10-10 17:48
The source appears to be that its mux/muy was set to be somewhere in that zoo, and then it tried to cast at where it thought you were (*totally* wrong) but because you could spot it (via detection) it printed that message. The bandaid fix will be in messaging, I think, the root cause only by rewriting monster ai and its use of mux/muy.

**Closed as completed** 2021-10-27 03:45 UTC
Labels: bug (minor)
