### ISSUE TITLE
No gold or gems generate in the wall on qstlb

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1427] opened 2021-01-19 20:52 UTC
On the level with the quest entrance, the walls are not filled with the usual gems and gold.

**Comment by NeroOneTrueKing** [comment] 2021-01-20 02:32
Duplicate of #955 
Fixing this means rewriting special level generation. Which would be nice, but is also really low on the priority list.

Closing, because one issue for the topic is enough.

**Closed as completed by NeroOneTrueKing** 2021-01-20 02:32 UTC
Labels: duplicate
