### ISSUE TITLE
Solid fog that lasts forever can be created

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#336] opened 2020-01-09 22:25 UTC
The blue rilmani spell fog can be created such that you end up with a patch that just won't go away. Not sure how to replicate, seems very rare. When it happened to me I had mvm rilmani combat, potentially a mix of poison clouds and solid fogs both mvm and mvu.

**Comment by NeroOneTrueKing** [comment] 2020-08-16 04:23
1) Cannot reproduce.
2) Poring over region.c, I can't see how this could happen without out-of-bounds memory shenanigans or some such.

Closing as unreproducible, and hopefully we'll never see this problem again?

**Closed as completed by NeroOneTrueKing** 2020-08-16 04:23 UTC
Labels: bug (minor), cannot reproduce
