### ISSUE TITLE
White dragon scales don't remove swimming from monsters when removed

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#334] opened 2020-01-09 22:21 UTC
I think it also leaves the magical breathing behind as well but I'm not sure. Not sure if this happens to other armor based monster extrinsics as well.

**Comment by NeroOneTrueKing** [comment] 2020-01-10 03:51
I am having difficulty reproducing this issue at all.
Can you consistently cause it?

**Comment by NeroOneTrueKing** [comment] 2020-04-10 00:20
I can't reproduce this bug; whatever was causing it may have been fixed since this was reported. Closing until it gets reproduced.

**Closed as completed by NeroOneTrueKing** 2020-04-10 00:20 UTC
Labels: fixed in dev, bug (minor)
